# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [1]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

In [2]:
import pandas as pd
df = pd.read_csv(url)

In [3]:
display(df)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [5]:
df.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='str')

In [6]:
low_total_claim_amount = df.loc[(df["total_claim_amount"] < 1000) & (df["response"] == "Yes")]
display (low_total_claim_amount)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
8,8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,...,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,A,1
15,15,CW49887,California,4626.801093,Yes,Basic,Master,2011-01-16,Employed,F,...,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,A,1
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2011-02-26,Employed,F,...,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A,2
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2011-02-28,Employed,F,...,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,A,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2011-02-07,Employed,F,...,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,A,2
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,2011-01-27,Employed,M,...,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,Four-Door Car,Medsize,A,1
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2011-02-07,Employed,F,...,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,A,2
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2011-02-03,Employed,F,...,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A,2
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,2011-01-26,Employed,M,...,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A,1

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [7]:
responded_yes = df.loc[df["response"] =="Yes"]
display(responded_yes)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
8,8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,...,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,A,1
15,15,CW49887,California,4626.801093,Yes,Basic,Master,2011-01-16,Employed,F,...,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,A,1
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2011-02-26,Employed,F,...,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A,2
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2011-02-28,Employed,F,...,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,A,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2011-02-07,Employed,F,...,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,A,2
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,2011-01-27,Employed,M,...,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,Four-Door Car,Medsize,A,1
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2011-02-07,Employed,F,...,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,A,2
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2011-02-03,Employed,F,...,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A,2
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,2011-01-26,Employed,M,...,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A,1

In [11]:
aveg_monthly_premium = (
    responded_yes
    .groupby(["policy_type", "gender"])
    .agg ({
        "monthly_premium_auto" : ["mean"],
        "customer_lifetime_value" :["mean"]
    })
)

display(aveg_monthly_premium)

                      monthly_premium_auto customer_lifetime_value
                                      mean                    mean
policy_type    gender
Corporate Auto F                 94.301775             7712.628736
               M                 92.188312             7944.465414
Personal Auto  F                 98.998148             8339.791842
               M                 91.085821             7448.383281
Special Auto   F                 92.314286             7691.584111
               M                 86.343750             8247.088702

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [12]:
display(df)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [24]:
total_customer = (
    df
    .groupby("state")
    .size()
)
display(total_customer)

state
Arizona       1937
California    4183
Nevada         993
Oregon        2909
Washington     888
dtype: int64

In [21]:
customer_more = total_customer[total_customer > 500]
display(customer_more)

state
Arizona       1937
California    4183
Nevada         993
Oregon        2909
Washington     888
Name: customer, dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [22]:
lifetime_value = (
    df
    .groupby(["education", "gender"])["customer_lifetime_value"]
    .agg(["max", "min", "median"])
)
display(lifetime_value)

                                     max          min       median
education            gender
Bachelor             F       73225.95652  1904.000852  5640.505303
                     M       67907.27050  1898.007675  5548.031892
College              F       61850.18803  1898.683686  5623.611187
                     M       61134.68307  1918.119700  6005.847375
Doctor               F       44856.11397  2395.570000  5332.462694
                     M       32677.34284  2267.604038  5577.669457
High School or Below F       55277.44589  2144.921535  6039.553187
                     M       83325.38119  1940.981221  6286.731006
Master               F       51016.06704  2417.777032  5729.855012
                     M       50568.25912  2272.307310  5579.099207

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [28]:
policies_sold = df.pivot_table(
    index="state",
    columns= "month",
    values="number_of_policies",
    aggfunc="sum"
)
display(policies_sold)

month          1     2
state
Arizona     3052  2864
California  6666  5901
Nevada      1493  1278
Oregon      4697  3969
Washington  1358  1225

i want to use the groupby method to see if i will get the same result or not. Though it gives me the same result, it does not present it as a perfect table like how the pivot table does it.

In [29]:
policies = (
    df
    .groupby(["state", "month"])["number_of_policies"]
    .agg("sum")
)
display(policies)

state       month
Arizona     1        3052
            2        2864
California  1        6666
            2        5901
Nevada      1        1493
            2        1278
Oregon      1        4697
            2        3969
Washington  1        1358
            2        1225
Name: number_of_policies, dtype: int64

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [39]:
number_policies = (
    df
    .groupby(["state", "month"])["number_of_policies"]
    .sum()
    .reset_index(name= "policies_sold")
)
display(number_policies)

        state  month  policies_sold
0     Arizona      1           3052
1     Arizona      2           2864
2  California      1           6666
3  California      2           5901
4      Nevada      1           1493
5      Nevada      2           1278
6      Oregon      1           4697
7      Oregon      2           3969
8  Washington      1           1358
9  Washington      2           1225

In [45]:
sorted_number_policies = number_policies.sort_values(by = "policies_sold", ascending = False)
display(sorted_number_policies)

        state  month  policies_sold
2  California      1           6666
3  California      2           5901
6      Oregon      1           4697
7      Oregon      2           3969
0     Arizona      1           3052
1     Arizona      2           2864
4      Nevada      1           1493
8  Washington      1           1358
5      Nevada      2           1278
9  Washington      2           1225

In [46]:
first_3 = sorted_number_policies.head(3)
display (first_3)

        state  month  policies_sold
2  California      1           6666
3  California      2           5901
6      Oregon      1           4697

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [48]:
display(df)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [50]:
effect_chan_res = (
    df
    .groupby(["sales_channel", "response"])
    .size()
    .reset_index(name="count")
)
display(effect_chan_res)

  sales_channel response  count
0         Agent       No   3379
1         Agent      Yes    742
2        Branch       No   2696
3        Branch      Yes    326
4   Call Center       No   1920
5   Call Center      Yes    221
6           Web       No   1449
7           Web      Yes    177

In [55]:
sum_effect_chan_res = (
    effect_chan_res
    .groupby("sales_channel")["count"]
    .sum()
    .reset_index(name="total_responses")
)
display(sum_effect_chan_res)

  sales_channel  total_responses
0         Agent             4121
1        Branch             3022
2   Call Center             2141
3           Web             1626

In [54]:
yes_response = effect_chan_res.loc[effect_chan_res["response"] == "Yes"]
display (yes_response)

  sales_channel response  count
1         Agent      Yes    742
3        Branch      Yes    326
5   Call Center      Yes    221
7           Web      Yes    177

Merging the two tables together thus sum_effect_chan_res and yes_response

In [58]:
combined_table = pd.merge(sum_effect_chan_res, yes_response, on="sales_channel", how="inner")
display(combined_table)

  sales_channel  total_responses response  count
0         Agent             4121      Yes    742
1        Branch             3022      Yes    326
2   Call Center             2141      Yes    221
3           Web             1626      Yes    177

Calculating for the rate of each sales channel using the count and the total responses

In [61]:
combined_table["response_rate"] = ((combined_table["count"]/combined_table["total_responses"]) * 100).round(2)
display(combined_table)

  sales_channel  total_responses response  count  response_rate
0         Agent             4121      Yes    742          18.01
1        Branch             3022      Yes    326          10.79
2   Call Center             2141      Yes    221          10.32
3           Web             1626      Yes    177          10.89